services:
  db:
    image: mysql:8
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: .
      target: backend  # берём только backend stage
    env_file: .env
    environment:
      DEBUG: 'True'
    entrypoint: /entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db

  frontend:
      image: node:20-alpine
      working_dir: /app/frontend
      volumes:
        - ./frontend:/app/frontend
        - /app/frontend/node_modules
      ports:
        - "5173:5173"
      command: sh -c "npm ci && npm run dev"

volumes:
  mysql_data:
  media_volume:
  static_volume: