# Generated by Django 5.2.11 on 2026-03-13 18:49
from os import path, listdir
from django.contrib.contenttypes.models import ContentType
from django.core.files import File
from django.db import migrations


def load_space_slides(apps, schema_editor):
    """Загружает дефолтные картинки в слайдер django админки."""
    Slider = apps.get_model('app', 'Slider')

    Image = apps.get_model('filer', 'Image')
    Folder = apps.get_model('filer', 'Folder')

    filer_image_ct = ContentType.objects.get_for_model(Image)

    # создаём папку c картинками в админке filer
    space_folder, _ = Folder.objects.get_or_create(name='Космос')
    images_path = path.join(path.dirname(__file__), 'default_slides')

    for idx, filename in enumerate(listdir(images_path)):
        filepath = path.join(images_path, filename)

        with open(filepath, 'rb') as f:
            filer_image = Image(
                folder=space_folder,
                original_filename=filename,
                polymorphic_ctype_id=filer_image_ct.id,
            )
            filer_image.file.save(filename, File(f), save=True)

        Slider.objects.create(
            title=path.splitext(filename)[0],
            image=filer_image,
            order=idx,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('easy_thumbnails', '0002_thumbnaildimensions'),
        ('filer', '0018_alter_file_options'), 
    ]

    operations = [
        migrations.RunPython(load_space_slides)
    ]
